/**
 * Single source of truth for all artwork photographs from the exhibition.
 * The 55 photos are split between the hero CCTV slider and the CamGrid wall —
 * each photo appears in exactly one place, never duplicated.
 *
 * Each id yields two assets generated by scripts/optimize-images.mjs:
 *   /images/artworks/<id>.webp        — 1600w, hero slider + popup
 *   /images/artworks/<id>-thumb.webp  — 400w,  100x100 grid tiles
 */
import { pad } from './format';

export interface Artwork {
  /** 1600w WebP, used by the hero slider and the full-screen popup. */
  src: string;
  /** 400w WebP, used by the 100x100 grid tiles. */
  thumbSrc: string;
  altKey: string;
  camId: string;
  location: string;
}

const IDS: readonly string[] = [
  'DSC01564-HDR',
  'DSC01571-HDR',
  'DSC01572-HDR',
  'DSC01576-HDR',
  'DSC01579-HDR',
  'DSC01580',
  'DSC01581__2_',
  'DSC01582-HDR',
  'DSC08946-HDR',
  'DSC08952-HDR',
  'DSC08955-HDR',
  'DSC08958-HDR',
  'DSC08961-HDR',
  'DSC08964-HDR',
  'DSC08967-HDR',
  'DSC08973-HDR',
  'DSC08988-HDR',
  'DSC08991-HDR',
  'DSC08997-HDR',
  'DSC09000-HDR',
  'DSC09007',
  'DSC09009-HDR',
  'DSC09012-HDR',
  'DSC09015-HDR',
  'DSC09021-HDR',
  'DSC09027-HDR',
  'DSC09030-HDR',
  'DSC09033-HDR',
  'DSC09041-HDR',
  'DSC09042-HDR',
  'DSC09045-HDR',
  'DSC09050-HDR',
  'DSC09053-HDR',
  'DSC09065-HDR',
  'DSC09066-HDR',
  'DSC09071',
  'DSC09093-HDR',
  'DSC09105-HDR',
  'DSC09110-HDR',
  'DSC09114-HDR',
  'DSC09117-HDR',
  'DSC09120-HDR',
  'DSC09125-HDR',
  'DSC09132-HDR',
  'DSC09137-HDR',
  'DSC09144-HDR',
  'DSC09148',
  'DSC09150-HDR',
  'DSC09167',
  'DSC09168-HDR',
  'DSC09179',
  'DSC09192',
  'DSC09195-HDR',
  'DSC09211_',
  'DSC09215',
] as const;

/** How many of the photos drive the hero slider. The rest fill the CamGrid. */
const HERO_COUNT = 8;

const ARTWORK_DIR = '/images/artworks';
const ARTWORK_ALT_KEY = 'feeds.artwork';
const ARTWORK_LOCATION = 'GALLERY';
const CAM_PREFIX = 'CAM';

const camLabel = (n: number) => `${CAM_PREFIX} ${pad(n, 2)}`;

const toArtwork = (id: string, i: number): Artwork => ({
  src: `${ARTWORK_DIR}/${id}.webp`,
  thumbSrc: `${ARTWORK_DIR}/${id}-thumb.webp`,
  altKey: ARTWORK_ALT_KEY,
  camId: camLabel(i + 1),
  location: ARTWORK_LOCATION,
});

/** Hero slider — the headline photos. Cycled in CamFeedSlider. */
export const HERO_ARTWORKS: readonly Artwork[] = IDS.slice(0, HERO_COUNT).map(
  toArtwork,
);

/** CamGrid wall — every other photo. No overlap with HERO_ARTWORKS. */
export const GRID_ARTWORKS: readonly Artwork[] = IDS.slice(HERO_COUNT).map(
  (id, i) => toArtwork(id, i + HERO_COUNT),
);

const TOTAL = IDS.length;

export const CAM_COUNT_LABEL = `${camLabel(1)}–${pad(TOTAL, 2)}`;
export const CAM_COUNT_TOTAL = pad(TOTAL, 3);
export const FEED_CYCLE_MS = 5500;
