/**
 * Catalogue list of works in Official. Unofficial. Belarus. (Venice 2026).
 * Source: docs/Art works list v01052026.docx.
 *
 * Titles stay bilingual (EN + BE) regardless of UI locale — the show itself
 * presents them that way. Medium and dimensions follow the participants
 * pattern (English in source, not in i18n). Photos live at
 * /images/works/<slug>.webp, generated by scripts/optimize-images.mjs.
 */
export interface ArtWork {
  /** Numbered file stem under public/images/works/, e.g. `01-field-of-wheat`. */
  slug: string;
  artist: string;
  titleEn: string;
  titleBe: string;
  year: string;
  medium: string;
  dimensions?: string;
}

export const WORKS: readonly ArtWork[] = [
  {
    slug: '01-field-of-wheat',
    artist: 'Sergey Grinevich',
    titleEn: 'Field of Wheat',
    titleBe: 'Пшанічнае Поле',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '250 × 150 cm',
  },
  {
    slug: '02-crucifixion',
    artist: 'Sergey Grinevich',
    titleEn: 'Crucifixion',
    titleBe: 'Распяцце',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '250 × 150 cm',
  },
  {
    slug: '03-crucifixion-i',
    artist: 'Sergey Grinevich',
    titleEn: 'Crucifixion I',
    titleBe: 'Распяцце I',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '150 × 250 cm',
  },
  {
    slug: '04-crucifixion-ii',
    artist: 'Sergey Grinevich',
    titleEn: 'Crucifixion II',
    titleBe: 'Распяцце II',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '150 × 250 cm',
  },
  {
    slug: '05-obedience',
    artist: 'Sergey Grinevich',
    titleEn: 'Obedience',
    titleBe: 'Паслухмянасць',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '250 × 150 cm',
  },
  {
    slug: '06-the-choir',
    artist: 'Sergey Grinevich',
    titleEn: 'The Choir',
    titleBe: 'Хор',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '120 × 200 cm',
  },
  {
    slug: '07-mary',
    artist: 'Sergey Grinevich',
    titleEn: 'Mary',
    titleBe: 'Марыя',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '81 × 140 cm',
  },
  {
    slug: '08-all-seeing-eye',
    artist: 'Sergey Grinevich',
    titleEn: 'All-seeing Eye',
    titleBe: 'Усевідушчае Вока',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '90 × 160 cm',
  },
  {
    slug: '09-in-search-of-spring',
    artist: 'Sergey Grinevich',
    titleEn: 'In Search of Spring',
    titleBe: 'Закліканне Вясны',
    year: '2026',
    medium: 'Acrylic on canvas',
    dimensions: '120 × 80 cm',
  },
  {
    slug: '10-spiders',
    artist: 'Vladimir Tsesler',
    titleEn: 'Spiders',
    titleBe: 'Павукі',
    year: '2026',
    medium: 'Reinforced steel',
    dimensions: '100 × 80 cm',
  },
  {
    slug: '11-dogs-of-europe',
    artist: 'Nicolai Khalezin',
    titleEn: 'Dogs of Europe',
    titleBe: 'Сабакі Эўропы',
    year: '2026',
    medium: 'Mixed material',
    dimensions: '2.5 m ⌀',
  },
  {
    slug: '12-surveillance-crucifix',
    artist: 'Daniella Kaliada with Natalia Kaliada',
    titleEn: 'Surveillance Crucifix',
    titleBe: 'Назіральнае Распяцце',
    year: '2026',
    medium: 'Mixed material',
    dimensions: '3.4 × 2 m',
  },
  {
    slug: '13-confessional-of-the-system',
    artist: 'Daniella Kaliada with Natalia Kaliada',
    titleEn: 'Confessional of the System',
    titleBe: 'Спаведальня Сістэмы',
    year: '2026',
    medium: 'Mixed material on 17th-century oak Dutch confessional',
    dimensions: '2.4 × 2.1 × 1.1 m',
  },
  {
    slug: '14-smell-of-dictatorship',
    artist: 'Ol.factory with Daniella Kaliada and Natalia Kaliada',
    titleEn: 'The Smell of Dictatorship',
    titleBe: 'Пах Дыктатуры',
    year: '2026',
    medium: 'Nebulised fragrance concentrate, cold-air diffusion',
  },
  {
    slug: '15-taste-of-nothing',
    artist: 'Rasmus Munk',
    titleEn: 'Taste of Nothing',
    titleBe: 'Смак Нічога',
    year: '2026',
    medium: 'Methylcellulose meringue with camellia oleracea',
    dimensions: '5 mm × 40 mm ⌀',
  },
  {
    slug: '16-sounds-of-silence',
    artist: 'Volha Podgaiskaya',
    titleEn: 'Sounds of Silence',
    titleBe: 'Гукі Цішыні',
    year: '2026',
    medium: 'Musical score for organ',
  },
  {
    slug: '17-wheat-field',
    artist: 'Curatorial Decision',
    titleEn: 'Wheat Field',
    titleBe: 'Пшанічнае Поле',
    year: '2026',
    medium: '90 cm dried wheat on soil and foam board',
    dimensions: '55 m²',
  },
  {
    slug: '18-straw-spider-making',
    artist: 'Curatorial Decision',
    titleEn: 'Straw Spider Making',
    titleBe: 'Выраб Саламянага Павука',
    year: '2026',
    medium: 'Five-analogue TV set-up with footage of traditional straw spider weaving',
  },
] as const;
